/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NBioBSPCLIJNI */

#ifndef _Included_NBioBSPCLIJNI
#define _Included_NBioBSPCLIJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NBioBSPCLIJNI
 * Method:    runStub
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NBioBSPCLIJNI_runStub
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
